title: WeField Projects
license:
  full_form: GNU AFFERO GENERAL PUBLIC LICENSE V3.0
  short_form: GNU AGPL v3.0
organization: WeField
description: Projects for WeField members.
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site
githuburl: "https://github.com/WeField-e-V/projects/"

gitter:
  gsoc:
    room: "https://gitter.im/coala/coala/gsoc"

gsoc_switch_month: 6

org:
  site_links:
    website: "https://www.wefield.org/"

plugins:
  - jekyll-netlify

# Build settings
exclude: [vendor, _projects/example.md]
markdown: kramdown
collections:
  projects:
    output: true
  reports:
    output: true
  faq:
    output: true

defaults:
  - scope:
      path: ''
      type: reports
    values:
      layout: report
      permalink: GSoC/:year/StatusReport/:title
